// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyEEVZ53ft72zf8UbKdUoDCW5Ocw08PZk',
    appId: '1:386000041584:android:21aab8ecd2f77a2f',
    messagingSenderId: '386000041584',
    projectId: 'api-project-386000041584',
    databaseURL: 'https://api-project-386000041584.firebaseio.com',
    storageBucket: 'api-project-386000041584.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUGh9wPhu-Vw8MdmwwytBzjGNNMfQufQ',
    appId: '1:386000041584:ios:090dad6606a467c91326b5',
    messagingSenderId: '386000041584',
    projectId: 'api-project-386000041584',
    databaseURL: 'https://api-project-386000041584.firebaseio.com',
    storageBucket: 'api-project-386000041584.appspot.com',
    androidClientId:
        '386000041584-4tg5m1ckvkh8vncvuldi9l6d27au6d6p.apps.googleusercontent.com',
    iosClientId:
        '386000041584-c82mgs9i7ii44pq7gkn9qm04vnrmqmt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.face_detection.RunnerTests',
  );
}
